name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        versions:
          # - minecraft: 1.8
          #   java: 8
          # - minecraft: 1.8.3
          #   java: 8
          # - minecraft: 1.8.4
          #   java: 8
          # - minecraft: 1.8.5
          #   java: 8
          # - minecraft: 1.8.6
          #   java: 8
          # - minecraft: 1.8.7
          #   java: 8
          # - minecraft: 1.8.8
          #   java: 8
          # - minecraft: 1.9
          #   java: 8
          # - minecraft: 1.9.2
          #   java: 8
          # - minecraft: 1.9.4
          #   java: 8
          # - minecraft: 1.10
          #   java: 8
          # - minecraft: 1.10.2
          #   java: 8
          # - minecraft: 1.11
          #   java: 8
          # - minecraft: 1.11.1
          #   java: 8
          # - minecraft: 1.11.2
          #   java: 8
          # - minecraft: 1.12
          #   java: 8
          # - minecraft: 1.12.1
          #   java: 8
          # - minecraft: 1.12.2
          #   java: 8
          # - minecraft: 1.13
          #   java: 8
          # - minecraft: 1.13.1
          #   java: 8
          # - minecraft: 1.13.2
          #   java: 8
          # - minecraft: 1.14
          #   java: 8
          # - minecraft: 1.14.1
          #   java: 8
          # - minecraft: 1.14.2
          #   java: 8
          # - minecraft: 1.14.3
          #   java: 8
          # - minecraft: 1.14.4
          #   java: 8
          # - minecraft: 1.15
          #   java: 8
          # - minecraft: 1.15.1
          #   java: 8
          # - minecraft: 1.15.2
          #   java: 8
          # - minecraft: 1.16.1
          #   java: 8
          # - minecraft: 1.16.2
          #   java: 8
          # - minecraft: 1.16.3
          #   java: 8
          # - minecraft: 1.16.4
          #   java: 8
          # - minecraft: 1.16.5
          #   java: 8
          # - minecraft: 1.17
          #   java: 17
          # - minecraft: 1.17.1
          #   java: 17
          # - minecraft: 1.18
          #   java: 17
          # - minecraft: 1.18.1
          #   java: 17
          # - minecraft: 1.18.2
          #   java: 17
          # - minecraft: 1.19
          #   java: 17
          # - minecraft: 1.19.1
          #   java: 17
          # - minecraft: 1.19.2
          #   java: 17
          # - minecraft: 1.19.3
          #   java: 17
          # - minecraft: 1.19.4
          #   java: 17
          # - minecraft: 1.20
          #   java: 21
          # - minecraft: 1.20.1
          #   java: 21
          # - minecraft: 1.20.2
          #   java: 21
          # - minecraft: 1.20.3
          #   java: 21
          # - minecraft: 1.20.4
          #   java: 21
          # - minecraft: 1.20.5
            # java: 21
          - minecraft: 1.20.6
            java: 21

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . \
        --file Dockerfile \
        --build-arg ARGS=" --remapped" \
        --build-arg JAVA_VERSION=${{ matrix.versions.java }} \
        --build-arg SPIGOT_VERSION=${{ matrix.versions.minecraft }} \
        --tag ${{ env.IMAGE_NAME }}:${{ matrix.versions.minecraft }} \
        --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.versions.minecraft }}

    - name: Publish to Registry
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
